FROM ubuntu:14.04.5

RUN apt-get update && apt-get install -y software-properties-common

RUN apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa -y

RUN apt-get update && apt-get -y install elmerfem-csc